name: eurosanpro
description: "A new Flutter project."

publish_to: 'none'  
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

# PACKAGES #
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.2.2
  intl: ^0.19.0
  logger: ^2.4.0
  url_launcher: ^6.3.0
  flutter_native_splash: ^2.4.0
  flutter_svg: ^2.0.10
  archive: ^3.6.1
  file_picker: ^8.0.5
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  lottie: ^3.1.2
  connectivity_plus: ^6.0.5
  syncfusion_flutter_pdf: ^26.2.14

  #Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Product Specific

  # Firebase
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.1
  cloud_firestore: ^5.4.1
  firebase_storage: ^12.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Local Assets
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/
    - assets/images/content/
    - assets/images/animations/

  # Local Fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800