class TTexts {
  static const String tLogin = "Login";
  static const String tSignUp = "Sign Up";

  static const String email = "E-mail";
  static const String password = "Password";
  static const String confirmPassword = "Confirm Password";
  static const String resetPassword = "Reset Password";
  static const String submit = "Submit";
  static const String rememberMe = "Remember Me";
  static const String forgotPassword = "Forgot Password?";
  static const String forgotPasswordTitle = "Forgot password";
  static const String forgotPasswordSubtitle = "Enter your email and we will send you a password reset link.";
  static const String notAMember = "Not a member?";
  static const String registerNow = "Register now";
  static const String alreadyHaveAnAccount = "Already have an account?";
  static const String logInNow = "Login now";
  static const String saveMyData = "Save my data";
  static const String firstName = "First Name";
  static const String lastName = "Last Name";
  static const String phoneNumber = "Phone Number";
  static const String dateOfBirth = "Date of Birth";
  static const String contractNumber = "Contract No";
  static const String location = "Location";

  static const String welcomeBack = "Welcome back you've been missed!";
  static const String letsCreateAccount = "Let's create an account for you!";
  static const String iAgreeTo = "I agree to";
  static const String privacyPolicy = "Privacy Policy";
  static const String and = "and";
  static const String termsOfUse = "Terms of use";
  static const String terms = "Terms";
  static const String beforeYouStart = "Before starting, we need more information.";
  static const String done = "Done";
  static const String resendEmail = "Resend Email";
  static const String changeYourPasswordTitle = "Password Reset Email Sent";
  static const String changeYourPasswordSubtitle = "Your Account Security is Our Priority! We've Sent You a Secure Link to Safely Change Your Password and Keep Your Account Protected.";
  static const String byTappingGetItNow = "By tapping Get It Now!, you will be charged, your subscription will auto-renew for the same price and package length until you cancel via Play Store settings, and you agree to our";

  static const String privacyPolicyText = '''
Privacy Policy
Last updated: November 04, 2024

This Privacy Policy outlines how EurosanDOOR, operated by SC SWING TRADE SRL ("we," "us," or "our"), collects, uses, and protects your personal data when you use the EurosanPro application ("Application"). By using our Service, you agree to the terms and practices described in this policy.

Interpretation and Definitions
Interpretation
Terms with capitalized initials have defined meanings, as specified below. These definitions apply whether they appear in singular or plural form.

Definitions
Account: A unique profile created for you to access parts of our Service.
Affiliate: An entity that controls, is controlled by, or is under common control with us, where "control" implies ownership of 50% or more of shares, equity, or voting rights.
Application: EurosanPro, the software program provided by the Company.
Company: Refers to EurosanDOOR, SC SWING TRADE SRL, located in Sovata, Jud: Mureș, str: Principală, nr: 72-74, Romania.
Country refers to: Romania.
Device: Any device that can access the Service, like a computer, mobile phone, or tablet.
Personal Data: Information that relates to an identified or identifiable individual.
Service: The EurosanPro application.
Service Provider: A third-party entity that processes data on behalf of the Company to assist in providing and analyzing our Service.
Usage Data: Information collected automatically, generated by using the Service or its infrastructure (e.g., the duration of a page visit).
You: The individual or entity accessing or using the Service.

Collecting and Using Your Personal Data
Types of Data Collected
Personal Data
While using our Service, we may ask you for certain personally identifiable information, which may include:

- Name, email address, phone number, and postal address
- National ID (CNP) and payment details (for services that require them)
- Location data and app usage data (collected automatically via cookies and analytics tools)
- Data from third-party providers, including social login information

Usage Data
Usage Data is collected automatically and may include your IP address, browser type, device identifiers, visited pages, time spent, mobile device ID, operating system, and diagnostic information.

Use of Your Personal Data
We use your data for various purposes, including:

- Service provision and improvement: To ensure optimal operation and user experience.
- Account management: To maintain your registration and access to features within the Service.
- Contract performance: For development, compliance, and management of contracts for products or services you purchase.
- Communication: To contact you via email, phone, or push notifications for updates or important Service information.
- Marketing: To send information about similar products or services unless you opt-out.
- Requests management: To handle your requests and customer service needs.
- Business transactions: In case of mergers, sales, or reorganizations, your data may be transferred.
- Analytics: For user experience optimization and data analysis.
- Security and compliance: To comply with legal requirements and protect user data.

Sharing of Your Data
We may share your data under the following conditions:

- Service Providers: For service facilitation and analysis.
- Business transfers: During mergers, acquisitions, or sale negotiations.
- Affiliates: With affiliated entities under the same data protection terms.
- Business partners: To provide offers and promotions.
- Public interactions: If you choose to interact in public areas of the Service.
- With consent: For other purposes with your explicit consent.

Data Retention and Storage
We retain Personal Data only as long as necessary for the purposes stated. Usage Data is generally kept for a shorter period unless needed for legal or security purposes. Data may be processed at our main office or transferred to servers outside Romania, with appropriate safeguards in place.

Your Data Rights
You have rights to access, amend, or delete your data:

- You can delete certain information within your account or request deletion directly from us.
- Certain legal obligations may require us to retain specific data.
- You may opt out of marketing and tracking data collection.

Security of Your Data
We use secure methods, including encryption, to protect your Personal Data. However, no online storage or transmission is completely secure, and we cannot guarantee absolute security.

Protection of Minors
Our Service is not intended for individuals under 13. If you are a parent and discover that your child has provided us with Personal Data, please contact us to delete the data. If your country requires parental consent, we will obtain it before collecting such information.

Links to Other Websites
Our Service may contain links to external websites. We are not responsible for the privacy practices of other sites.

Changes to This Privacy Policy
We may update this Privacy Policy periodically. Updates will be posted on this page with a revised "Last updated" date. We encourage regular review of this Policy.

Contact Us
If you have any questions about this Privacy Policy, you can contact us:

By email: swingtrademarketing@yahoo.com
    ''';

  static const String termsOfUseText = '''
Termeni și Condiții (Terms of Use)

Termeni și Condiții pentru EurosanPRO
Ultima actualizare: November 04, 2024
Acești Termeni și Condiții stabilesc regulile de utilizare a aplicației EurosanPRO, deținută de EurosanDOOR, marcă deținută de SC SWING TRADE SRL („noi”, „aplicația”, „compania”).

1. Denumirea aplicației și drepturile de proprietate
    • Aplicația se numește EurosanPRO și este deținută de EurosanDOOR, parte a SC SWING TRADE SRL.

2. Eligibilitate
    • Aplicația poate fi utilizată doar de persoane care au împlinit vârsta de 18 ani.
    • Utilizarea aplicației este destinată doar clienților care au achiziționat un produs premium specific.

3. Cont și acces
    • Pentru a accesa aplicația, utilizatorii trebuie să achiziționeze produsul premium și să preplătească abonamentul pentru aplicație și funcționalitățile acesteia.

4. Responsabilitățile utilizatorilor
    • Utilizatorii trebuie să respecte toate legile și reglementările aplicabile atunci când utilizează aplicația.
    • Este interzisă utilizarea aplicației în scopuri ilegale, de hărțuire, sau pentru a afecta funcționarea aplicației.

5. Drepturi de proprietate intelectuală
    • Tot conținutul aplicației (cod sursă, design, logo-uri, mărci comerciale) este deținut de EurosanDOOR, parte a SC SWING TRADE SRL.
    • Este interzisă utilizarea acestui conținut fără permisiunea scrisă prealabilă.

6. Plăți și abonamente
    • Aplicația funcționează pe bază de abonament.
    • Odată ce o plată a fost realizată, nu este posibilă rambursarea acesteia, dar utilizatorii pot anula abonamentul la orice moment.

7. Încetarea serviciului
    • Dacă utilizatorul decide să își încheie abonamentul, accesul la aplicație va fi revocat.

8. Limitarea răspunderii
    • SC SWING TRADE SRL nu este responsabilă pentru daune rezultate din utilizarea aplicației, inclusiv pierderi de date sau întreruperi ale serviciului.

9. Proprietate intelectuală
    • Toate drepturile de proprietate intelectuală asupra aplicației aparțin EurosanDOOR, parte a SC SWING TRADE SRL. Utilizatorii nu au dreptul de a folosi elementele de proprietate intelectuală fără consimțământ.

10. Rezolvarea disputelor
    • Orice dispută va fi soluționată prin arbitraj sau în fața instanțelor din România.

11. Legea aplicabilă
    • Termenii și Condițiile sunt guvernate de legislația din România.

12. Modificări ale Termenilor și Condițiilor
    • Orice modificare a acestor termeni va fi notificată utilizatorilor prin email.
    ''';
}