// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6cyNG1mN0VDBPyN_NpH3rSuQnOZ2b76E',
    appId: '1:319216908601:web:04404041c70c3c3a9550e8',
    messagingSenderId: '319216908601',
    projectId: 'eurosanpro-fc510',
    authDomain: 'eurosanpro-fc510.firebaseapp.com',
    storageBucket: 'eurosanpro-fc510.appspot.com',
    measurementId: 'G-P19S2NP1V2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvo3ZarEeJB6AGvr_NP6uV4AMl77DTNIs',
    appId: '1:319216908601:android:f38ced64996e1e2a9550e8',
    messagingSenderId: '319216908601',
    projectId: 'eurosanpro-fc510',
    storageBucket: 'eurosanpro-fc510.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQGf2v5WvBoQvro3pNiIIOL5l2vKGPaoE',
    appId: '1:319216908601:ios:e0ec542e2fe3d2769550e8',
    messagingSenderId: '319216908601',
    projectId: 'eurosanpro-fc510',
    storageBucket: 'eurosanpro-fc510.appspot.com',
    androidClientId: '319216908601-7ilvtmkfaggadvl21ippe09oold5tp8l.apps.googleusercontent.com',
    iosClientId: '319216908601-au9ehl5pdqrsnmo49n625kjkvd5d638g.apps.googleusercontent.com',
    iosBundleId: 'com.example.eurosanpro',
  );

}